title: <p align="center"> Chijioke E </p>

logo: "/images/chijioke.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chijioke/">LinkedIn</a> |
  <a href="https://github.com/smilycj">GitHub</a>
  </p>
  
  <p align="justify">
  An avid Data Analyst 
  <br><br>
  I am currently exploring supply chain projects 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
