title: <p align="center"> Chijioke E (CJ) </p>


logo: "/images/chijioke.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chijioke/">LinkedIn</a> |
  <a href="https://github.com/smilycj">GitHub</a>
  </p>
  
  <p align="justify">
  Just a  guy obsessed with data and thrilled gaining insight with every opportunity
  <br><br>
  Interested in Analysis and ML projects
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
